apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo-weights-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 64Gi
