apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo-weights-disk-nogpu
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 128Gi
