kind: Pod
apiVersion: v1
metadata:
  name: yololens-nogpu
  labels:
    app: yololens-nogpu
spec:
  nodeSelector:
    agentpool: cpupool
  containers:
    - name: yololens-nogpu
      image: adcaline/yololens-nogpu
      ports:
        - containerPort: 80
      volumeMounts:
        - name: weights
          mountPath: /mnt/weights
      resources:
        limits:
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: COSMOS_HOST
          valueFrom:
            secretKeyRef:
              name: cosmosdb
              key: host
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: cosmosdb
              key: key
        - name: COSMOS_DATABASE
          valueFrom:
            secretKeyRef:
              name: cosmosdb
              key: database
        - name: COSMOS_COLLECTION
          valueFrom:
            secretKeyRef:
              name: cosmosdb
              key: collection
  volumes:
    - name: weights
      persistentVolumeClaim:
        claimName: yolo-weights-disk-nogpu
  restartPolicy: OnFailure
---
kind: Service
apiVersion: v1
metadata:
  name: yololens-nogpu
spec:
  type: LoadBalancer
  selector:
    app: yololens-nogpu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
